name: UncommonRhymesV2 Benchmark

on:
  pull_request:
    paths:
      - "app.py"
      - "rhyme_core/**"
      - "scripts/**"
      - "tests/**"
      - "data/**"
      - ".github/workflows/benchmark.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  bench:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml pytest hypothesis

      - run: pip install ruff mypy
      - run: ruff check . && ruff format --check .
      - run: mypy rhyme_core

      - name: Ensure results dir
        run: mkdir -p results

      - name: Run pytest (determinism & props)
        run: pytest -q

      - name: Run benchmark (cap=20)
        run: |
          python scripts/benchmark.py \
            --terms data/test_terms.txt \
            --goldens data/golden_expectations.yaml \
            --out results/benchmark.csv \
            --cap 20

      - name: Generate reports
        run: |
          python scripts/bench_report.py --csv results/benchmark.csv --out results/benchmark_report.html
          python scripts/bench_summarize.py --csv results/benchmark.csv --out results/summary.md
          python scripts/coverage_report.py --csv results/benchmark.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-${{ matrix.os }}-py${{ matrix.python }}
          path: |
            results/benchmark.csv
            results/benchmark_report.html
            results/benchmark.queries_used.txt
            results/summary.md

      - name: Comment summary on PR
        if: ${{ github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest' && matrix.python == '3.11' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'results/summary.md';
            let body = 'Benchmark summary not found.';
            if (fs.existsSync(path)) body = fs.readFileSync(path, 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
