name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -U pip wheel
      - run: pip install -r requirements.txt ruff mypy
      - run: ruff check . && ruff format --check .
      - run: mypy rhyme_core || true
      - run: pytest
      - name: Import smoke
        run: python - <<'PY'
import importlib; importlib.import_module("app"); print("OK")
PY
