name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true          # pull LFS files if you use them

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install Git LFS (for safety)
        run: git lfs install --local

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Replace both 'romado33' and 'UncommonRhymesV2' below if needed
          git remote add space "https://romado33:${HF_TOKEN}@huggingface.co/spaces/romado33/UncommonRhymesV2.git"
          # Push the current commit to the Space's main branch
          git push --force space HEAD:main
