name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install Git LFS (for safety)
        run: git lfs install --local

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: romado33
          HF_SPACE: UncommonRhymesV2
        run: |
          set -e
          # auth’d remote (prevents 429 and credential prompts)
          git remote remove space 2>/dev/null || true
          git remote add space "https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${HF_SPACE}.git"

          # modest retry in case of transient 429s
          n=0
          until [ $n -ge 3 ]; do
            git push --force space HEAD:main && break
            n=$((n+1))
            echo "Push failed, retry $n/3 after backoff..."
            sleep $((10 * n))
          done